version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper 
    restart: always
    networks:
      default:
        ipv4_address: 172.20.0.6
    ports:
      - 2181:2181

networks:
  default:
    external:
      name: elk-kafka-network
