version: '3'
services:
  kibana:
    image: kibana
    container_name: kibana 
    restart: always
    networks:
      default:
        ipv4_address: 172.20.0.5
    environment:
      - ELASTICSEARCH_URL=http://172.20.0.2:9200
    ports:
      - 5601:5601
    external_links:
      - elasticsearch-one:elasticsearch-one
      - elasticsearch-two:elasticsearch-two
               
networks:
  default:
    external:
      name: elk-kafka-network
